
s3:
  endpoint:
  accessKey:
  secretKey:
  bucket:

backups:
  - name:
    schedule: "0 * * * *"
    triggerImmediately: false
    host: "http+tcp://127.0.0.1:8529"
    database: "test"
    user: "root"
    password: ""
    historySize: 5
    collections:
      - some
