apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arangocado.fullname" . }}
  labels:
    {{- include "arangocado.labels" . | nindent 4 }}
data:
  config: |
    checkInterval: "{{ .Values.checkInterval }}"
    cacheDir:  "{{ .Values.cacheDir }}"

    s3:
      {{- toYaml .Values.s3 | nindent 6 }}

    backups:
      {{- toYaml .Values.backups | nindent 6 }}
